export const projectData = [
    {
        id: "1",
        title: "Pathfinder",
        firstIcon: "./assets/language/python.png",
        secondIcon: "./assets/misc/pygame.png",
        thirdIcon: "./assets/misc/oop.png",
        description: "Interactive implementation of A-star path-finding algorithm visualizer",
        firstPoint: "Real time relational node calculations and visual path traversal",
        secondPoint: "A-star implementation running 30% faster than average algorithms",
        thirdPoint: "",
        demoImage: "./assets/demo/",
        codeImage: "./assets/code/pathfinder.png",
        video: "./assets/demo/pathfinder.mp4",
        github: "https://github.com/jflin0808/PathFinder",
    },
    {
        id: "2",
        title: "Recipe Hub",
        firstIcon: "./assets/language/python.png",
        secondIcon: "./assets/web/django.jpg",
        thirdIcon: "./assets/misc/docker.png",
        description: "Fully functional web application allowing users to create and share recipes online",
        firstPoint: "Functional CRUD operations for users and recipes",
        secondPoint: "Engineered REST API and set up relational data models",
        thirdPoint: "Created Docker image of app and deployed to Google Cloud",
        demoImage: "./assets/demo/recipehub.png",
        codeImage: "./assets/code/recipehub.png",
        video: "",
        github: "https://github.com/jflin0808/RecipeHub",
    },
    {
        id: "3",
        title: "LoL Analysis",
        firstIcon: "./assets/language/python.png",
        secondIcon: "./assets/misc/api.png",
        thirdIcon: "./assets/misc/plotly.svg",
        description: "Data analysis of top 300 players",
        firstPoint: "Accessed Riot's REST  API to access and store official game data",
        secondPoint: "Multiple requests made to different URLS to gather JSON files",
        thirdPoint: "Dashboard creation with plotly and html elements",
        demoImage: "./assets/demo/lol.png",
        codeImage: "./assets/code/lol.png",
        video: "",
        github: "https://github.com/jflin0808/LoL-Analysis",
    },
    {
        id: "4",
        title: "Test Prediction",
        firstIcon: "./assets/language/python.png",
        secondIcon: "./assets/ds/jupyter.png",
        thirdIcon: "./assets/misc/plotly.svg",
        description: "Analysis and Model of student data in relationship with posttest data",
        firstPoint: "Full EDA to determine key features and relationships",
        secondPoint: "Linear regression model implementation using sklearn",
        thirdPoint: "Relationships and analysis plotted using seaborn and plotly",
        demoImage: "./assets/demo/student.png",
        codeImage: "./assets/code/student.png",
        video: "",
        github: "",
    },
]