export const projectData = [
    {
        id: "1",
        title: "Pathfinder",
        firstIcon: "./assets/language/python.png",
        secondIcon: "./assets/misc/pygame.png",
        thirdIcon: "./assets/misc/oop/png",
        description: "Interactive implementation of A-star path-finding algorithm visualizer",
        firstPoint: "Real time relational node calculations and visual path traversal",
        secondPoint: "A-star implementation running 30% faster than average algorithms",
        thirdPoint: "",
        demoImage: "./assets/demo/",
        codeImage: "./assets/code/pathfinder.png",
        video: "./assets/demo/pathfinder.mp4",
        github: "https://github.com/jflin0808/PathFinder",
    },
    {
        id: "2",
        title: "Recipe Hub",
        firstIcon: "./assets/language/python.png",
        secondIcon: "./assets/web/django.jpg",
        thirdIcon: "./assets/misc/docker.png",
        description: "Fully functional web application allowing users to create and share recipes online",
        firstPoint: "Functional CRUD operations for users and recipes",
        secondPoint: "Engineered REST API and set up relational data models",
        thirdPoint: "Created Docker image of app and deployed to Google Cloud",
        demoImage: "./assets/demo/recipehub.png",
        codeImage: "./assets/code/recipehub.png",
        video: "./assets/demo/",
        github: "https://github.com/jflin0808/RecipeHub",
    },
    {
        id: "3",
        title: "LoL Analysis",
        firstIcon: "./assets/language/python.png",
        secondIcon: "./assets/misc/api.png",
        thirdIcon: "./assets/misc/plotly.svg",
        description: "",
        firstPoint: "",
        secondPoint: "",
        thirdPoint: "",
        demoImage: "./assets/demo/lol.png",
        codeImage: "./assets/code/lol.png",
        video: "./assets/demo/",
        github: "",
    },
    {
        id: "4",
        title: "Test Prediction",
        firstIcon: "./assets/",
        secondIcon: "./assets/",
        thirdIcon: "./assets/",
        description: "",
        firstPoint: "",
        secondPoint: "",
        thirdPoint: "",
        demoImage: "./assets/demo/student.png",
        codeImage: "./assets/code/student.png",
        video: "./assets/demo/",
        github: "",
    },
    {
        id: "5",
        title: "Sudoku Solver",
        firstIcon: "./assets/",
        secondIcon: "./assets/",
        thirdIcon: "./assets/",
        description: "",
        firstPoint: "",
        secondPoint: "",
        thirdPoint: "",
        demoImage: "./assets/demo/sudoku.png",
        codeImage: "./assets/code/sudoku.png",
        video: "./assets/demo/",
        github: "",
    },
    {
        id: "6",
        title: "Bank Application",
        firstIcon: "./assets/",
        secondIcon: "./assets/",
        thirdIcon: "./assets/",
        description: "",
        firstPoint: "",
        secondPoint: "",
        thirdPoint: "",
        demoImage: "./assets/demo/bank.png",
        codeImage: "./assets/code/bank.png",
        video: "./assets/demo/",
        github: "",
    },
    {
        id: "7",
        title: "Linear Regression",
        firstIcon: "./assets/",
        secondIcon: "./assets/",
        thirdIcon: "./assets/",
        description: "",
        firstPoint: "",
        secondPoint: "",
        thirdPoint: "",
        demoImage: "./assets/demo/",
        codeImage: "./assets/code/linear.png",
        video: "./assets/demo/linear.mp4",
        github: "",
    },
    {
        id: "8",
        title: "Logistic Regression",
        firstIcon: "./assets/",
        secondIcon: "./assets/",
        thirdIcon: "./assets/",
        description: "",
        firstPoint: "",
        secondPoint: "",
        thirdPoint: "",
        demoImage: "./assets/demo/",
        codeImage: "./assets/code/logistic.png",
        video: "./assets/demo/logistic.mp4",
        github: "",
    },
    {
        id: "9",
        title: "Neural Network",
        firstIcon: "./assets/",
        secondIcon: "./assets/",
        thirdIcon: "./assets/",
        description: "",
        firstPoint: "",
        secondPoint: "",
        thirdPoint: "",
        demoImage: "./assets/demo/",
        codeImage: "./assets/code/neural.png",
        video: "./assets/demo/neural.mp4",
        github: "",
    },
    {
        id: "10",
        title: "Unsupervised Learning",
        firstIcon: "./assets/",
        secondIcon: "./assets/",
        thirdIcon: "./assets/",
        description: "",
        firstPoint: "",
        secondPoint: "",
        thirdPoint: "",
        demoImage: "./assets/demo/",
        codeImage: "./assets/code/unsupervised.png",
        video: "./assets/demo/unsupervised.mp4",
        github: "",
    },
    
]